### ISSUE TITLE
Redmine 4 commit breaks Redmine 3 compat

### ISSUE THREAD

**Issue by bviktor** [tckz/redmine-wiki_graphviz_plugin#16]
Title says it all. Makes migration preparations rather difficult.

**Comment by tckz** [comment]
You can use older version of the plugin for old redmine.

**Comment by bviktor** [comment]
Yeah, I know that. That's like saying "oh you want Firefox 65? Good, install Win10 then."

People running Redmine 3 will miss any new features and bug fixes coming along.

**Comment by tckz** [comment]
I have no longer to use Redmine 3.x. 
Thus there is no reason for me to support Redmine 3.

**Comment by bviktor** [comment]
You might as well delete the plugin from GitHub then, since apparently you only care about yourself :)
