### ISSUE TITLE
Error with PDF export

### ISSUE THREAD

**Issue by dwerner-d** [tckz/redmine-wiki_graphviz_plugin#18]
Hello,

I've just installed the Graphviz plugin and it's working very well.

When trying to do a PDF export of the Wiki page, I get the following error message in the PDF document:
Error executing the **graphviz_link** macro (Missing template wiki_graphviz/macro with {:locale=>[:de, :en], :formats=>[:pdf], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :rsb]}...)

The HTML export is working fine. Is there anything missing in my setup or in the configuration?

Regards
David

**Comment by tckz** [comment]
When exporting wiki page to PDF, There is no way to embed image which is generated from wiki macro.
